// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqM2O-eVuQi7lOKBZarJ4GkEwMSFzLm2c',
    appId: '1:19718707626:web:c2e7e735b471888eca73d3',
    messagingSenderId: '19718707626',
    projectId: 'ecommerce-flutter093022',
    authDomain: 'ecommerce-flutter093022.firebaseapp.com',
    storageBucket: 'ecommerce-flutter093022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFyRxM6aR-jn-T5zDfIoyTUMQ-iwu3mSk',
    appId: '1:19718707626:android:907c6e88b2548ff4ca73d3',
    messagingSenderId: '19718707626',
    projectId: 'ecommerce-flutter093022',
    storageBucket: 'ecommerce-flutter093022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFWXzZUSjCWSDwHcZERWXABzuXi3FNzk',
    appId: '1:19718707626:ios:1d5ebd6edae30602ca73d3',
    messagingSenderId: '19718707626',
    projectId: 'ecommerce-flutter093022',
    storageBucket: 'ecommerce-flutter093022.appspot.com',
    iosClientId: '19718707626-l7a3k69uoi002ai0t9s08pmb663e43a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
